servers:
  local:
    default: true  # if server name is not provided in tool calls, this Spark History Server is used
    url: "http://localhost:18080"
    # Optional authentication (can also use environment variables)
    # auth:
    #   username: "your_username"  # or use SHS_SPARK_USERNAME env var
    #   password: "your_password"  # or use SHS_SPARK_PASSWORD env var
    #   token: "your_token"       # or use SHS_SPARK_TOKEN env var

  # Production server example
  # production:
  #   url: "https://spark-history.company.com:18080"
  #   auth:
      # Use environment variables for production
      # username: ${SHS_SPARK_USERNAME}
      # password: ${SHS_SPARK_PASSWORD}
      # token: ${SHS_SPARK_TOKEN}

  # Staging server example
  # staging:
  #   url: "https://staging-spark-history.company.com:18080"
  #   auth:
      # username: "staging_user"
      # token: "staging_token"

mcp:
  transports:
    - streamable-http # streamable-http or stdio. you can only specify one right now.
  port: "18888"
  debug: true

# Environment Variables:
# SHS_SPARK_USERNAME - Default username for authentication
# SHS_SPARK_PASSWORD - Default password for authentication
# SHS_SPARK_TOKEN - Default token for authentication
# SHS_MCP_PORT - Port for MCP server (default: 18888)
# SHS_MCP_DEBUG - Enable debug mode (default: false)
