apiVersion: v2
name: spark-history-mcp
description: A Helm chart for Spark History Server MCP
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - spark
  - mcp
  - analytics
  - performance
  - history-server
home: https://github.com/DeepDiagnostix-AI/spark-history-server-mcp
sources:
  - https://github.com/DeepDiagnostix-AI/spark-history-server-mcp
maintainers:
  - name: Manabu McCloskey
    email: Manabu.McCloskey@gmail.com
  - name: Vara Bonthu
    email: vara.bonthu@gmail.com
annotations:
  category: Analytics
