name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    - name: Enable caching and define a custom cache key suffix
      id: setup-uv
      uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba
      with:
        enable-cache: true

    - name: Run pre-commit
      run: uv run pre-commit run --all-files --show-diff-on-failure
